### ISSUE TITLE
projectdirectorycheck does not override the PROJECT field in the response

### ISSUE THREAD

**Issue by GROwen** [amazeeio/lagoon-cli#156] opened 2020-10-06 06:42 UTC
**Describe the bug**
When `lagoon list variables` is executed from the directory of a git repo other than the [project] being queried the response includes the name of the project as it appears in the command and not the project the variable is associated with.

Scenario: lagoon-cli config `projectdirectorycheckdisable: true` is not defined and cmd is run from a git repo of a project other than the [project] being queried

**To Reproduce**
`other-project-dir $ lagoon list variables -p example-project`

**Expected behaviour**
`15000	other-project	project 	global 	EXAMPLE_VAR`

**Actual behaviour**
`15000	example-project	project 	global 	EXAMPLE_VAR`

I was caught out by this because I was focusing on the PROJECT field in the response.

**Desktop (please complete the following information):**
 - OS: OS X
 - lagoon 0.9.3

**Comment by shreddedbacon** [comment] 2020-10-11 23:29
That repository local check is a feature I am in two minds about. I don't use it, and I don't know how many people do. Most issues are caused by it, so disabling it seems to be the way to go.

I have an open PR to disable it by default, and only enable it if someone wants to use it.
I am also hesitant to spend time on fixing the problems it has. If you or your team use the local directory check feature, I would love if you could let us know how it could work better for you (and if you wanted to have a crack at fixing the issues), otherwise I would love to deprecate it entirely.

The variable list command is the most frequent command impacted this feature too because it is a bit clunky when defining project/environment in general.

We are planning out a refresh of the CLI at the moment to change a lot about how commands are used, and this will be to primarily support lagoon2.

**Comment by shreddedbacon** [comment] 2021-04-14 23:15
Closing this as it will likely be properly corrected in a refresh of the CLI. But for now the project directory check is opt-in in the latest CLI release, so this shouldn't crop up as often.

**Closed by shreddedbacon** 2021-04-14 23:15 UTC
Labels: discussion
